// Code generated by gi; DO NOT EDIT.
package main

import (
	"reflect"

	"github.com/emicklei/dot"
	"github.com/emicklei/gi"
)

func init() {
	values := map[string]reflect.Value{
		"Directed":                     reflect.ValueOf(dot.Directed),
		"MermaidBottomToTop":           reflect.ValueOf(dot.MermaidBottomToTop),
		"MermaidFlowchart":             reflect.ValueOf(dot.MermaidFlowchart),
		"MermaidGraph":                 reflect.ValueOf(dot.MermaidGraph),
		"MermaidLeftToRight":           reflect.ValueOf(dot.MermaidLeftToRight),
		"MermaidRightToLeft":           reflect.ValueOf(dot.MermaidRightToLeft),
		"MermaidShapeAsymmetric":       reflect.ValueOf(dot.MermaidShapeAsymmetric),
		"MermaidShapeCircle":           reflect.ValueOf(dot.MermaidShapeCircle),
		"MermaidShapeCirle":            reflect.ValueOf(dot.MermaidShapeCirle),
		"MermaidShapeCylinder":         reflect.ValueOf(dot.MermaidShapeCylinder),
		"MermaidShapeHexagon":          reflect.ValueOf(dot.MermaidShapeHexagon),
		"MermaidShapeParallelogram":    reflect.ValueOf(dot.MermaidShapeParallelogram),
		"MermaidShapeParallelogramAlt": reflect.ValueOf(dot.MermaidShapeParallelogramAlt),
		"MermaidShapeRhombus":          reflect.ValueOf(dot.MermaidShapeRhombus),
		"MermaidShapeRound":            reflect.ValueOf(dot.MermaidShapeRound),
		"MermaidShapeStadium":          reflect.ValueOf(dot.MermaidShapeStadium),
		"MermaidShapeSubroutine":       reflect.ValueOf(dot.MermaidShapeSubroutine),
		"MermaidShapeTrapezoid":        reflect.ValueOf(dot.MermaidShapeTrapezoid),
		"MermaidShapeTrapezoidAlt":     reflect.ValueOf(dot.MermaidShapeTrapezoidAlt),
		"MermaidTopDown":               reflect.ValueOf(dot.MermaidTopDown),
		"MermaidTopToBottom":           reflect.ValueOf(dot.MermaidTopToBottom),
		"NewGraph":                     reflect.ValueOf(dot.NewGraph),
		"NewIndentWriter":              reflect.ValueOf(dot.NewIndentWriter),
		"Strict":                       reflect.ValueOf(dot.Strict),
		"Sub":                          reflect.ValueOf(dot.Sub),
		"Undirected":                   reflect.ValueOf(dot.Undirected),
	}
	types := map[string]reflect.Type{
		"AttributesMap":   reflect.TypeFor[dot.AttributesMap](),
		"ClusterOption":   reflect.TypeFor[dot.ClusterOption](),
		"Edge":            reflect.TypeFor[dot.Edge](),
		"Graph":           reflect.TypeFor[dot.Graph](),
		"GraphTypeOption": reflect.TypeFor[dot.GraphTypeOption](),
		"HTML":            reflect.TypeFor[dot.HTML](),
		"IndentWriter":    reflect.TypeFor[dot.IndentWriter](),
		"Literal":         reflect.TypeFor[dot.Literal](),
		"Node":            reflect.TypeFor[dot.Node](),
	}
	gi.RegisterPackage("github.com/emicklei/dot", values, types)
}
