// Code generated by cmd/genstdlib/main.go; DO NOT EDIT.
package internal

import (
	"reflect"
	i1 "archive/tar"
	i2 "archive/zip"
	i3 "bufio"
	i4 "bytes"
	i5 "compress/bzip2"
	i6 "compress/flate"
	i7 "compress/gzip"
	i8 "compress/lzw"
	i9 "compress/zlib"
	i11 "container/list"
	i12 "container/ring"
	i14 "crypto"
	i15 "crypto/aes"
	i16 "crypto/cipher"
	i17 "crypto/des"
	i18 "crypto/dsa"
	i19 "crypto/ecdsa"
	i20 "crypto/ed25519"
	i21 "crypto/elliptic"
	i25 "crypto/rc4"
	i26 "crypto/rsa"
	i31 "crypto/tls"
	i32 "crypto/x509"
	i33 "database/sql"
	i34 "database/sql/driver"
	i35 "encoding/ascii85"
	i36 "encoding/asn1"
	i37 "encoding/base32"
	i38 "encoding/base64"
	i40 "encoding/csv"
	i41 "encoding/gob"
	i42 "encoding/hex"
	i43 "encoding/json"
	i44 "encoding/pem"
	i45 "encoding/xml"
	i47 "expvar"
	i48 "flag"
	i54 "hash/maphash"
	i56 "html/template"
	i57 "image"
	i58 "image/color"
	i60 "image/draw"
	i61 "image/gif"
	i62 "image/jpeg"
	i63 "image/png"
	i64 "index/suffixarray"
	i65 "io"
	i66 "io/fs"
	i68 "log"
	i69 "log/slog"
	i70 "log/syslog"
	i72 "math/big"
	i75 "math/rand"
	i76 "mime"
	i77 "mime/multipart"
	i78 "mime/quotedprintable"
	i79 "net"
	i80 "net/http"
	i81 "net/http/cgi"
	i82 "net/http/cookiejar"
	i84 "net/http/httptest"
	i85 "net/http/httptrace"
	i86 "net/http/httputil"
	i88 "net/mail"
	i89 "net/rpc"
	i91 "net/smtp"
	i92 "net/textproto"
	i93 "net/url"
	i94 "os"
	i95 "os/exec"
	i97 "os/user"
	i100 "plugin"
	i101 "regexp"
	i102 "regexp/syntax"
	i104 "strconv"
	i105 "strings"
	i106 "sync"
	i107 "sync/atomic"
	i108 "text/scanner"
	i109 "text/tabwriter"
	i110 "text/template"
	i111 "text/template/parse"
	i112 "time"
	i113 "unicode"
)

// stdtypes maps package paths to their exported types as reflect.Value not reflect.Type
var stdtypes = map[string]map[string]reflect.Value{}

func init() {
	stdtypes["archive/tar"] = map[string]reflect.Value{
		"Format": makeReflect[i1.Format](),
		"Header": makeReflect[i1.Header](),
		"Reader": makeReflect[i1.Reader](),
		"Writer": makeReflect[i1.Writer](),
	}
	stdtypes["archive/zip"] = map[string]reflect.Value{
		"File": makeReflect[i2.File](),
		"FileHeader": makeReflect[i2.FileHeader](),
		"ReadCloser": makeReflect[i2.ReadCloser](),
		"Reader": makeReflect[i2.Reader](),
		"Writer": makeReflect[i2.Writer](),
	}
	stdtypes["bufio"] = map[string]reflect.Value{
		"ReadWriter": makeReflect[i3.ReadWriter](),
		"Reader": makeReflect[i3.Reader](),
		"Scanner": makeReflect[i3.Scanner](),
		"Writer": makeReflect[i3.Writer](),
	}
	stdtypes["bytes"] = map[string]reflect.Value{
		"Buffer": makeReflect[i4.Buffer](),
		"Reader": makeReflect[i4.Reader](),
	}
	stdtypes["compress/bzip2"] = map[string]reflect.Value{
		"StructuralError": makeReflect[i5.StructuralError](),
	}
	stdtypes["compress/flate"] = map[string]reflect.Value{
		"CorruptInputError": makeReflect[i6.CorruptInputError](),
		"InternalError": makeReflect[i6.InternalError](),
		"ReadError": makeReflect[i6.ReadError](),
		"WriteError": makeReflect[i6.WriteError](),
		"Writer": makeReflect[i6.Writer](),
	}
	stdtypes["compress/gzip"] = map[string]reflect.Value{
		"Header": makeReflect[i7.Header](),
		"Reader": makeReflect[i7.Reader](),
		"Writer": makeReflect[i7.Writer](),
	}
	stdtypes["compress/lzw"] = map[string]reflect.Value{
		"Order": makeReflect[i8.Order](),
		"Reader": makeReflect[i8.Reader](),
		"Writer": makeReflect[i8.Writer](),
	}
	stdtypes["compress/zlib"] = map[string]reflect.Value{
		"Writer": makeReflect[i9.Writer](),
	}
	stdtypes["container/list"] = map[string]reflect.Value{
		"Element": makeReflect[i11.Element](),
		"List": makeReflect[i11.List](),
	}
	stdtypes["container/ring"] = map[string]reflect.Value{
		"Ring": makeReflect[i12.Ring](),
	}
	stdtypes["crypto"] = map[string]reflect.Value{
		"DecrypterOpts": makeReflect[i14.DecrypterOpts](),
		"Hash": makeReflect[i14.Hash](),
		"PrivateKey": makeReflect[i14.PrivateKey](),
		"PublicKey": makeReflect[i14.PublicKey](),
	}
	stdtypes["crypto/aes"] = map[string]reflect.Value{
		"KeySizeError": makeReflect[i15.KeySizeError](),
	}
	stdtypes["crypto/cipher"] = map[string]reflect.Value{
		"StreamReader": makeReflect[i16.StreamReader](),
		"StreamWriter": makeReflect[i16.StreamWriter](),
	}
	stdtypes["crypto/des"] = map[string]reflect.Value{
		"KeySizeError": makeReflect[i17.KeySizeError](),
	}
	stdtypes["crypto/dsa"] = map[string]reflect.Value{
		"ParameterSizes": makeReflect[i18.ParameterSizes](),
		"Parameters": makeReflect[i18.Parameters](),
		"PrivateKey": makeReflect[i18.PrivateKey](),
		"PublicKey": makeReflect[i18.PublicKey](),
	}
	stdtypes["crypto/ecdsa"] = map[string]reflect.Value{
		"PrivateKey": makeReflect[i19.PrivateKey](),
		"PublicKey": makeReflect[i19.PublicKey](),
	}
	stdtypes["crypto/ed25519"] = map[string]reflect.Value{
		"Options": makeReflect[i20.Options](),
	}
	stdtypes["crypto/elliptic"] = map[string]reflect.Value{
		"CurveParams": makeReflect[i21.CurveParams](),
	}
	stdtypes["crypto/rc4"] = map[string]reflect.Value{
		"Cipher": makeReflect[i25.Cipher](),
		"KeySizeError": makeReflect[i25.KeySizeError](),
	}
	stdtypes["crypto/rsa"] = map[string]reflect.Value{
		"CRTValue": makeReflect[i26.CRTValue](),
		"OAEPOptions": makeReflect[i26.OAEPOptions](),
		"PKCS1v15DecryptOptions": makeReflect[i26.PKCS1v15DecryptOptions](),
		"PSSOptions": makeReflect[i26.PSSOptions](),
		"PrecomputedValues": makeReflect[i26.PrecomputedValues](),
		"PrivateKey": makeReflect[i26.PrivateKey](),
		"PublicKey": makeReflect[i26.PublicKey](),
	}
	stdtypes["crypto/tls"] = map[string]reflect.Value{
		"AlertError": makeReflect[i31.AlertError](),
		"Certificate": makeReflect[i31.Certificate](),
		"CertificateRequestInfo": makeReflect[i31.CertificateRequestInfo](),
		"CertificateVerificationError": makeReflect[i31.CertificateVerificationError](),
		"CipherSuite": makeReflect[i31.CipherSuite](),
		"ClientAuthType": makeReflect[i31.ClientAuthType](),
		"ClientHelloInfo": makeReflect[i31.ClientHelloInfo](),
		"ClientSessionState": makeReflect[i31.ClientSessionState](),
		"Config": makeReflect[i31.Config](),
		"Conn": makeReflect[i31.Conn](),
		"ConnectionState": makeReflect[i31.ConnectionState](),
		"CurveID": makeReflect[i31.CurveID](),
		"Dialer": makeReflect[i31.Dialer](),
		"ECHRejectionError": makeReflect[i31.ECHRejectionError](),
		"EncryptedClientHelloKey": makeReflect[i31.EncryptedClientHelloKey](),
		"QUICConfig": makeReflect[i31.QUICConfig](),
		"QUICConn": makeReflect[i31.QUICConn](),
		"QUICEncryptionLevel": makeReflect[i31.QUICEncryptionLevel](),
		"QUICEvent": makeReflect[i31.QUICEvent](),
		"QUICEventKind": makeReflect[i31.QUICEventKind](),
		"QUICSessionTicketOptions": makeReflect[i31.QUICSessionTicketOptions](),
		"RecordHeaderError": makeReflect[i31.RecordHeaderError](),
		"RenegotiationSupport": makeReflect[i31.RenegotiationSupport](),
		"SessionState": makeReflect[i31.SessionState](),
		"SignatureScheme": makeReflect[i31.SignatureScheme](),
	}
	stdtypes["crypto/x509"] = map[string]reflect.Value{
		"CertPool": makeReflect[i32.CertPool](),
		"Certificate": makeReflect[i32.Certificate](),
		"CertificateInvalidError": makeReflect[i32.CertificateInvalidError](),
		"CertificateRequest": makeReflect[i32.CertificateRequest](),
		"ConstraintViolationError": makeReflect[i32.ConstraintViolationError](),
		"ExtKeyUsage": makeReflect[i32.ExtKeyUsage](),
		"HostnameError": makeReflect[i32.HostnameError](),
		"InsecureAlgorithmError": makeReflect[i32.InsecureAlgorithmError](),
		"InvalidReason": makeReflect[i32.InvalidReason](),
		"KeyUsage": makeReflect[i32.KeyUsage](),
		"OID": makeReflect[i32.OID](),
		"PEMCipher": makeReflect[i32.PEMCipher](),
		"PolicyMapping": makeReflect[i32.PolicyMapping](),
		"PublicKeyAlgorithm": makeReflect[i32.PublicKeyAlgorithm](),
		"RevocationList": makeReflect[i32.RevocationList](),
		"RevocationListEntry": makeReflect[i32.RevocationListEntry](),
		"SignatureAlgorithm": makeReflect[i32.SignatureAlgorithm](),
		"SystemRootsError": makeReflect[i32.SystemRootsError](),
		"UnhandledCriticalExtension": makeReflect[i32.UnhandledCriticalExtension](),
		"UnknownAuthorityError": makeReflect[i32.UnknownAuthorityError](),
		"VerifyOptions": makeReflect[i32.VerifyOptions](),
	}
	stdtypes["database/sql"] = map[string]reflect.Value{
		"ColumnType": makeReflect[i33.ColumnType](),
		"Conn": makeReflect[i33.Conn](),
		"DB": makeReflect[i33.DB](),
		"DBStats": makeReflect[i33.DBStats](),
		"IsolationLevel": makeReflect[i33.IsolationLevel](),
		"NamedArg": makeReflect[i33.NamedArg](),
		"NullBool": makeReflect[i33.NullBool](),
		"NullByte": makeReflect[i33.NullByte](),
		"NullFloat64": makeReflect[i33.NullFloat64](),
		"NullInt16": makeReflect[i33.NullInt16](),
		"NullInt32": makeReflect[i33.NullInt32](),
		"NullInt64": makeReflect[i33.NullInt64](),
		"NullString": makeReflect[i33.NullString](),
		"NullTime": makeReflect[i33.NullTime](),
		"Out": makeReflect[i33.Out](),
		"Row": makeReflect[i33.Row](),
		"Rows": makeReflect[i33.Rows](),
		"Stmt": makeReflect[i33.Stmt](),
		"Tx": makeReflect[i33.Tx](),
		"TxOptions": makeReflect[i33.TxOptions](),
	}
	stdtypes["database/sql/driver"] = map[string]reflect.Value{
		"IsolationLevel": makeReflect[i34.IsolationLevel](),
		"NamedValue": makeReflect[i34.NamedValue](),
		"NotNull": makeReflect[i34.NotNull](),
		"Null": makeReflect[i34.Null](),
		"RowsAffected": makeReflect[i34.RowsAffected](),
		"TxOptions": makeReflect[i34.TxOptions](),
		"Value": makeReflect[i34.Value](),
	}
	stdtypes["encoding/ascii85"] = map[string]reflect.Value{
		"CorruptInputError": makeReflect[i35.CorruptInputError](),
	}
	stdtypes["encoding/asn1"] = map[string]reflect.Value{
		"BitString": makeReflect[i36.BitString](),
		"Enumerated": makeReflect[i36.Enumerated](),
		"Flag": makeReflect[i36.Flag](),
		"RawValue": makeReflect[i36.RawValue](),
		"StructuralError": makeReflect[i36.StructuralError](),
		"SyntaxError": makeReflect[i36.SyntaxError](),
	}
	stdtypes["encoding/base32"] = map[string]reflect.Value{
		"CorruptInputError": makeReflect[i37.CorruptInputError](),
		"Encoding": makeReflect[i37.Encoding](),
	}
	stdtypes["encoding/base64"] = map[string]reflect.Value{
		"CorruptInputError": makeReflect[i38.CorruptInputError](),
		"Encoding": makeReflect[i38.Encoding](),
	}
	stdtypes["encoding/csv"] = map[string]reflect.Value{
		"ParseError": makeReflect[i40.ParseError](),
		"Reader": makeReflect[i40.Reader](),
		"Writer": makeReflect[i40.Writer](),
	}
	stdtypes["encoding/gob"] = map[string]reflect.Value{
		"CommonType": makeReflect[i41.CommonType](),
		"Decoder": makeReflect[i41.Decoder](),
		"Encoder": makeReflect[i41.Encoder](),
	}
	stdtypes["encoding/hex"] = map[string]reflect.Value{
		"InvalidByteError": makeReflect[i42.InvalidByteError](),
	}
	stdtypes["encoding/json"] = map[string]reflect.Value{
		"Decoder": makeReflect[i43.Decoder](),
		"Delim": makeReflect[i43.Delim](),
		"Encoder": makeReflect[i43.Encoder](),
		"InvalidUTF8Error": makeReflect[i43.InvalidUTF8Error](),
		"InvalidUnmarshalError": makeReflect[i43.InvalidUnmarshalError](),
		"MarshalerError": makeReflect[i43.MarshalerError](),
		"Number": makeReflect[i43.Number](),
		"SyntaxError": makeReflect[i43.SyntaxError](),
		"Token": makeReflect[i43.Token](),
		"UnmarshalFieldError": makeReflect[i43.UnmarshalFieldError](),
		"UnmarshalTypeError": makeReflect[i43.UnmarshalTypeError](),
		"UnsupportedTypeError": makeReflect[i43.UnsupportedTypeError](),
		"UnsupportedValueError": makeReflect[i43.UnsupportedValueError](),
	}
	stdtypes["encoding/pem"] = map[string]reflect.Value{
		"Block": makeReflect[i44.Block](),
	}
	stdtypes["encoding/xml"] = map[string]reflect.Value{
		"Attr": makeReflect[i45.Attr](),
		"Decoder": makeReflect[i45.Decoder](),
		"Encoder": makeReflect[i45.Encoder](),
		"EndElement": makeReflect[i45.EndElement](),
		"Name": makeReflect[i45.Name](),
		"ProcInst": makeReflect[i45.ProcInst](),
		"StartElement": makeReflect[i45.StartElement](),
		"SyntaxError": makeReflect[i45.SyntaxError](),
		"TagPathError": makeReflect[i45.TagPathError](),
		"Token": makeReflect[i45.Token](),
		"UnmarshalError": makeReflect[i45.UnmarshalError](),
		"UnsupportedTypeError": makeReflect[i45.UnsupportedTypeError](),
	}
	stdtypes["expvar"] = map[string]reflect.Value{
		"Float": makeReflect[i47.Float](),
		"Int": makeReflect[i47.Int](),
		"KeyValue": makeReflect[i47.KeyValue](),
		"Map": makeReflect[i47.Map](),
		"String": makeReflect[i47.String](),
	}
	stdtypes["flag"] = map[string]reflect.Value{
		"ErrorHandling": makeReflect[i48.ErrorHandling](),
		"Flag": makeReflect[i48.Flag](),
		"FlagSet": makeReflect[i48.FlagSet](),
	}
	stdtypes["hash/maphash"] = map[string]reflect.Value{
		"Hash": makeReflect[i54.Hash](),
		"Seed": makeReflect[i54.Seed](),
	}
	stdtypes["html/template"] = map[string]reflect.Value{
		"CSS": makeReflect[i56.CSS](),
		"Error": makeReflect[i56.Error](),
		"ErrorCode": makeReflect[i56.ErrorCode](),
		"HTML": makeReflect[i56.HTML](),
		"HTMLAttr": makeReflect[i56.HTMLAttr](),
		"JS": makeReflect[i56.JS](),
		"JSStr": makeReflect[i56.JSStr](),
		"Srcset": makeReflect[i56.Srcset](),
		"Template": makeReflect[i56.Template](),
		"URL": makeReflect[i56.URL](),
	}
	stdtypes["image"] = map[string]reflect.Value{
		"Alpha": makeReflect[i57.Alpha](),
		"Alpha16": makeReflect[i57.Alpha16](),
		"CMYK": makeReflect[i57.CMYK](),
		"Config": makeReflect[i57.Config](),
		"Gray": makeReflect[i57.Gray](),
		"Gray16": makeReflect[i57.Gray16](),
		"NRGBA": makeReflect[i57.NRGBA](),
		"NRGBA64": makeReflect[i57.NRGBA64](),
		"NYCbCrA": makeReflect[i57.NYCbCrA](),
		"Paletted": makeReflect[i57.Paletted](),
		"Point": makeReflect[i57.Point](),
		"RGBA": makeReflect[i57.RGBA](),
		"RGBA64": makeReflect[i57.RGBA64](),
		"Rectangle": makeReflect[i57.Rectangle](),
		"Uniform": makeReflect[i57.Uniform](),
		"YCbCr": makeReflect[i57.YCbCr](),
		"YCbCrSubsampleRatio": makeReflect[i57.YCbCrSubsampleRatio](),
	}
	stdtypes["image/color"] = map[string]reflect.Value{
		"Alpha": makeReflect[i58.Alpha](),
		"Alpha16": makeReflect[i58.Alpha16](),
		"CMYK": makeReflect[i58.CMYK](),
		"Gray": makeReflect[i58.Gray](),
		"Gray16": makeReflect[i58.Gray16](),
		"NRGBA": makeReflect[i58.NRGBA](),
		"NRGBA64": makeReflect[i58.NRGBA64](),
		"NYCbCrA": makeReflect[i58.NYCbCrA](),
		"RGBA": makeReflect[i58.RGBA](),
		"RGBA64": makeReflect[i58.RGBA64](),
		"YCbCr": makeReflect[i58.YCbCr](),
	}
	stdtypes["image/draw"] = map[string]reflect.Value{
		"Op": makeReflect[i60.Op](),
	}
	stdtypes["image/gif"] = map[string]reflect.Value{
		"GIF": makeReflect[i61.GIF](),
		"Options": makeReflect[i61.Options](),
	}
	stdtypes["image/jpeg"] = map[string]reflect.Value{
		"FormatError": makeReflect[i62.FormatError](),
		"Options": makeReflect[i62.Options](),
		"UnsupportedError": makeReflect[i62.UnsupportedError](),
	}
	stdtypes["image/png"] = map[string]reflect.Value{
		"CompressionLevel": makeReflect[i63.CompressionLevel](),
		"Encoder": makeReflect[i63.Encoder](),
		"EncoderBuffer": makeReflect[i63.EncoderBuffer](),
		"FormatError": makeReflect[i63.FormatError](),
		"UnsupportedError": makeReflect[i63.UnsupportedError](),
	}
	stdtypes["index/suffixarray"] = map[string]reflect.Value{
		"Index": makeReflect[i64.Index](),
	}
	stdtypes["io"] = map[string]reflect.Value{
		"LimitedReader": makeReflect[i65.LimitedReader](),
		"OffsetWriter": makeReflect[i65.OffsetWriter](),
		"PipeReader": makeReflect[i65.PipeReader](),
		"PipeWriter": makeReflect[i65.PipeWriter](),
		"SectionReader": makeReflect[i65.SectionReader](),
	}
	stdtypes["io/fs"] = map[string]reflect.Value{
		"FileMode": makeReflect[i66.FileMode](),
		"PathError": makeReflect[i66.PathError](),
	}
	stdtypes["log"] = map[string]reflect.Value{
		"Logger": makeReflect[i68.Logger](),
	}
	stdtypes["log/slog"] = map[string]reflect.Value{
		"Attr": makeReflect[i69.Attr](),
		"HandlerOptions": makeReflect[i69.HandlerOptions](),
		"JSONHandler": makeReflect[i69.JSONHandler](),
		"Kind": makeReflect[i69.Kind](),
		"Level": makeReflect[i69.Level](),
		"LevelVar": makeReflect[i69.LevelVar](),
		"Logger": makeReflect[i69.Logger](),
		"Record": makeReflect[i69.Record](),
		"Source": makeReflect[i69.Source](),
		"TextHandler": makeReflect[i69.TextHandler](),
		"Value": makeReflect[i69.Value](),
	}
	stdtypes["log/syslog"] = map[string]reflect.Value{
		"Priority": makeReflect[i70.Priority](),
		"Writer": makeReflect[i70.Writer](),
	}
	stdtypes["math/big"] = map[string]reflect.Value{
		"Accuracy": makeReflect[i72.Accuracy](),
		"ErrNaN": makeReflect[i72.ErrNaN](),
		"Float": makeReflect[i72.Float](),
		"Int": makeReflect[i72.Int](),
		"Rat": makeReflect[i72.Rat](),
		"RoundingMode": makeReflect[i72.RoundingMode](),
		"Word": makeReflect[i72.Word](),
	}
	stdtypes["math/rand"] = map[string]reflect.Value{
		"Rand": makeReflect[i75.Rand](),
		"Zipf": makeReflect[i75.Zipf](),
	}
	stdtypes["mime"] = map[string]reflect.Value{
		"WordDecoder": makeReflect[i76.WordDecoder](),
		"WordEncoder": makeReflect[i76.WordEncoder](),
	}
	stdtypes["mime/multipart"] = map[string]reflect.Value{
		"FileHeader": makeReflect[i77.FileHeader](),
		"Form": makeReflect[i77.Form](),
		"Part": makeReflect[i77.Part](),
		"Reader": makeReflect[i77.Reader](),
		"Writer": makeReflect[i77.Writer](),
	}
	stdtypes["mime/quotedprintable"] = map[string]reflect.Value{
		"Reader": makeReflect[i78.Reader](),
		"Writer": makeReflect[i78.Writer](),
	}
	stdtypes["net"] = map[string]reflect.Value{
		"AddrError": makeReflect[i79.AddrError](),
		"DNSConfigError": makeReflect[i79.DNSConfigError](),
		"DNSError": makeReflect[i79.DNSError](),
		"Dialer": makeReflect[i79.Dialer](),
		"Flags": makeReflect[i79.Flags](),
		"IPAddr": makeReflect[i79.IPAddr](),
		"IPConn": makeReflect[i79.IPConn](),
		"IPNet": makeReflect[i79.IPNet](),
		"Interface": makeReflect[i79.Interface](),
		"InvalidAddrError": makeReflect[i79.InvalidAddrError](),
		"KeepAliveConfig": makeReflect[i79.KeepAliveConfig](),
		"ListenConfig": makeReflect[i79.ListenConfig](),
		"MX": makeReflect[i79.MX](),
		"NS": makeReflect[i79.NS](),
		"OpError": makeReflect[i79.OpError](),
		"ParseError": makeReflect[i79.ParseError](),
		"Resolver": makeReflect[i79.Resolver](),
		"SRV": makeReflect[i79.SRV](),
		"TCPAddr": makeReflect[i79.TCPAddr](),
		"TCPConn": makeReflect[i79.TCPConn](),
		"TCPListener": makeReflect[i79.TCPListener](),
		"UDPAddr": makeReflect[i79.UDPAddr](),
		"UDPConn": makeReflect[i79.UDPConn](),
		"UnixAddr": makeReflect[i79.UnixAddr](),
		"UnixConn": makeReflect[i79.UnixConn](),
		"UnixListener": makeReflect[i79.UnixListener](),
		"UnknownNetworkError": makeReflect[i79.UnknownNetworkError](),
	}
	stdtypes["net/http"] = map[string]reflect.Value{
		"Client": makeReflect[i80.Client](),
		"ConnState": makeReflect[i80.ConnState](),
		"Cookie": makeReflect[i80.Cookie](),
		"CrossOriginProtection": makeReflect[i80.CrossOriginProtection](),
		"Dir": makeReflect[i80.Dir](),
		"HTTP2Config": makeReflect[i80.HTTP2Config](),
		"MaxBytesError": makeReflect[i80.MaxBytesError](),
		"ProtocolError": makeReflect[i80.ProtocolError](),
		"Protocols": makeReflect[i80.Protocols](),
		"PushOptions": makeReflect[i80.PushOptions](),
		"Request": makeReflect[i80.Request](),
		"Response": makeReflect[i80.Response](),
		"ResponseController": makeReflect[i80.ResponseController](),
		"SameSite": makeReflect[i80.SameSite](),
		"ServeMux": makeReflect[i80.ServeMux](),
		"Server": makeReflect[i80.Server](),
		"Transport": makeReflect[i80.Transport](),
	}
	stdtypes["net/http/cgi"] = map[string]reflect.Value{
		"Handler": makeReflect[i81.Handler](),
	}
	stdtypes["net/http/cookiejar"] = map[string]reflect.Value{
		"Jar": makeReflect[i82.Jar](),
		"Options": makeReflect[i82.Options](),
	}
	stdtypes["net/http/httptest"] = map[string]reflect.Value{
		"ResponseRecorder": makeReflect[i84.ResponseRecorder](),
		"Server": makeReflect[i84.Server](),
	}
	stdtypes["net/http/httptrace"] = map[string]reflect.Value{
		"ClientTrace": makeReflect[i85.ClientTrace](),
		"DNSDoneInfo": makeReflect[i85.DNSDoneInfo](),
		"DNSStartInfo": makeReflect[i85.DNSStartInfo](),
		"GotConnInfo": makeReflect[i85.GotConnInfo](),
		"WroteRequestInfo": makeReflect[i85.WroteRequestInfo](),
	}
	stdtypes["net/http/httputil"] = map[string]reflect.Value{
		"ClientConn": makeReflect[i86.ClientConn](),
		"ProxyRequest": makeReflect[i86.ProxyRequest](),
		"ReverseProxy": makeReflect[i86.ReverseProxy](),
		"ServerConn": makeReflect[i86.ServerConn](),
	}
	stdtypes["net/mail"] = map[string]reflect.Value{
		"Address": makeReflect[i88.Address](),
		"AddressParser": makeReflect[i88.AddressParser](),
		"Message": makeReflect[i88.Message](),
	}
	stdtypes["net/rpc"] = map[string]reflect.Value{
		"Call": makeReflect[i89.Call](),
		"Client": makeReflect[i89.Client](),
		"Request": makeReflect[i89.Request](),
		"Response": makeReflect[i89.Response](),
		"Server": makeReflect[i89.Server](),
		"ServerError": makeReflect[i89.ServerError](),
	}
	stdtypes["net/smtp"] = map[string]reflect.Value{
		"Client": makeReflect[i91.Client](),
		"ServerInfo": makeReflect[i91.ServerInfo](),
	}
	stdtypes["net/textproto"] = map[string]reflect.Value{
		"Conn": makeReflect[i92.Conn](),
		"Error": makeReflect[i92.Error](),
		"Pipeline": makeReflect[i92.Pipeline](),
		"ProtocolError": makeReflect[i92.ProtocolError](),
		"Reader": makeReflect[i92.Reader](),
		"Writer": makeReflect[i92.Writer](),
	}
	stdtypes["net/url"] = map[string]reflect.Value{
		"Error": makeReflect[i93.Error](),
		"EscapeError": makeReflect[i93.EscapeError](),
		"InvalidHostError": makeReflect[i93.InvalidHostError](),
		"URL": makeReflect[i93.URL](),
		"Userinfo": makeReflect[i93.Userinfo](),
	}
	stdtypes["os"] = map[string]reflect.Value{
		"File": makeReflect[i94.File](),
		"LinkError": makeReflect[i94.LinkError](),
		"ProcAttr": makeReflect[i94.ProcAttr](),
		"Process": makeReflect[i94.Process](),
		"ProcessState": makeReflect[i94.ProcessState](),
		"Root": makeReflect[i94.Root](),
		"SyscallError": makeReflect[i94.SyscallError](),
	}
	stdtypes["os/exec"] = map[string]reflect.Value{
		"Cmd": makeReflect[i95.Cmd](),
		"Error": makeReflect[i95.Error](),
		"ExitError": makeReflect[i95.ExitError](),
	}
	stdtypes["os/user"] = map[string]reflect.Value{
		"Group": makeReflect[i97.Group](),
		"UnknownGroupError": makeReflect[i97.UnknownGroupError](),
		"UnknownGroupIdError": makeReflect[i97.UnknownGroupIdError](),
		"UnknownUserError": makeReflect[i97.UnknownUserError](),
		"UnknownUserIdError": makeReflect[i97.UnknownUserIdError](),
		"User": makeReflect[i97.User](),
	}
	stdtypes["plugin"] = map[string]reflect.Value{
		"Plugin": makeReflect[i100.Plugin](),
		"Symbol": makeReflect[i100.Symbol](),
	}
	stdtypes["regexp"] = map[string]reflect.Value{
		"Regexp": makeReflect[i101.Regexp](),
	}
	stdtypes["regexp/syntax"] = map[string]reflect.Value{
		"EmptyOp": makeReflect[i102.EmptyOp](),
		"Error": makeReflect[i102.Error](),
		"ErrorCode": makeReflect[i102.ErrorCode](),
		"Flags": makeReflect[i102.Flags](),
		"Inst": makeReflect[i102.Inst](),
		"InstOp": makeReflect[i102.InstOp](),
		"Op": makeReflect[i102.Op](),
		"Prog": makeReflect[i102.Prog](),
		"Regexp": makeReflect[i102.Regexp](),
	}
	stdtypes["strconv"] = map[string]reflect.Value{
		"NumError": makeReflect[i104.NumError](),
	}
	stdtypes["strings"] = map[string]reflect.Value{
		"Builder": makeReflect[i105.Builder](),
		"Reader": makeReflect[i105.Reader](),
		"Replacer": makeReflect[i105.Replacer](),
	}
	stdtypes["sync"] = map[string]reflect.Value{
		"Cond": makeReflect[i106.Cond](),
		"Map": makeReflect[i106.Map](),
		"Mutex": makeReflect[i106.Mutex](),
		"Once": makeReflect[i106.Once](),
		"Pool": makeReflect[i106.Pool](),
		"RWMutex": makeReflect[i106.RWMutex](),
		"WaitGroup": makeReflect[i106.WaitGroup](),
	}
	stdtypes["sync/atomic"] = map[string]reflect.Value{
		"Bool": makeReflect[i107.Bool](),
		"Int32": makeReflect[i107.Int32](),
		"Int64": makeReflect[i107.Int64](),
		"Uint32": makeReflect[i107.Uint32](),
		"Uint64": makeReflect[i107.Uint64](),
		"Uintptr": makeReflect[i107.Uintptr](),
		"Value": makeReflect[i107.Value](),
	}
	stdtypes["text/scanner"] = map[string]reflect.Value{
		"Position": makeReflect[i108.Position](),
		"Scanner": makeReflect[i108.Scanner](),
	}
	stdtypes["text/tabwriter"] = map[string]reflect.Value{
		"Writer": makeReflect[i109.Writer](),
	}
	stdtypes["text/template"] = map[string]reflect.Value{
		"ExecError": makeReflect[i110.ExecError](),
		"Template": makeReflect[i110.Template](),
	}
	stdtypes["text/template/parse"] = map[string]reflect.Value{
		"ActionNode": makeReflect[i111.ActionNode](),
		"BoolNode": makeReflect[i111.BoolNode](),
		"BranchNode": makeReflect[i111.BranchNode](),
		"BreakNode": makeReflect[i111.BreakNode](),
		"ChainNode": makeReflect[i111.ChainNode](),
		"CommandNode": makeReflect[i111.CommandNode](),
		"CommentNode": makeReflect[i111.CommentNode](),
		"ContinueNode": makeReflect[i111.ContinueNode](),
		"DotNode": makeReflect[i111.DotNode](),
		"FieldNode": makeReflect[i111.FieldNode](),
		"IdentifierNode": makeReflect[i111.IdentifierNode](),
		"IfNode": makeReflect[i111.IfNode](),
		"ListNode": makeReflect[i111.ListNode](),
		"Mode": makeReflect[i111.Mode](),
		"NilNode": makeReflect[i111.NilNode](),
		"NodeType": makeReflect[i111.NodeType](),
		"NumberNode": makeReflect[i111.NumberNode](),
		"PipeNode": makeReflect[i111.PipeNode](),
		"Pos": makeReflect[i111.Pos](),
		"RangeNode": makeReflect[i111.RangeNode](),
		"StringNode": makeReflect[i111.StringNode](),
		"TemplateNode": makeReflect[i111.TemplateNode](),
		"TextNode": makeReflect[i111.TextNode](),
		"Tree": makeReflect[i111.Tree](),
		"VariableNode": makeReflect[i111.VariableNode](),
		"WithNode": makeReflect[i111.WithNode](),
	}
	stdtypes["time"] = map[string]reflect.Value{
		"Duration": makeReflect[i112.Duration](),
		"Location": makeReflect[i112.Location](),
		"Month": makeReflect[i112.Month](),
		"ParseError": makeReflect[i112.ParseError](),
		"Ticker": makeReflect[i112.Ticker](),
		"Time": makeReflect[i112.Time](),
		"Timer": makeReflect[i112.Timer](),
		"Weekday": makeReflect[i112.Weekday](),
	}
	stdtypes["unicode"] = map[string]reflect.Value{
		"CaseRange": makeReflect[i113.CaseRange](),
		"Range16": makeReflect[i113.Range16](),
		"Range32": makeReflect[i113.Range32](),
		"RangeTable": makeReflect[i113.RangeTable](),
	}
}
