// Code generated by cmd/genstdlib/main.go; DO NOT EDIT.
package pkg

import (
	"reflect"
	i1 "archive/tar"
	i2 "archive/zip"
	i3 "bufio"
	i4 "bytes"
	i5 "compress/bzip2"
	i6 "compress/flate"
	i7 "compress/gzip"
	i8 "compress/lzw"
	i9 "compress/zlib"
	i11 "container/list"
	i12 "container/ring"
	i14 "crypto"
	i15 "crypto/aes"
	i16 "crypto/cipher"
	i17 "crypto/des"
	i18 "crypto/dsa"
	i19 "crypto/ecdh"
	i20 "crypto/ecdsa"
	i21 "crypto/ed25519"
	i22 "crypto/elliptic"
	i26 "crypto/mlkem"
	i28 "crypto/rc4"
	i29 "crypto/rsa"
	i32 "crypto/sha3"
	i35 "crypto/tls"
	i36 "crypto/x509"
	i37 "database/sql"
	i38 "database/sql/driver"
	i39 "encoding/ascii85"
	i40 "encoding/asn1"
	i41 "encoding/base32"
	i42 "encoding/base64"
	i44 "encoding/csv"
	i45 "encoding/gob"
	i46 "encoding/hex"
	i47 "encoding/json"
	i48 "encoding/pem"
	i49 "encoding/xml"
	i51 "expvar"
	i52 "flag"
	i58 "hash/maphash"
	i60 "html/template"
	i61 "image"
	i62 "image/color"
	i64 "image/draw"
	i65 "image/gif"
	i66 "image/jpeg"
	i67 "image/png"
	i68 "index/suffixarray"
	i69 "io"
	i70 "io/fs"
	i72 "log"
	i73 "log/slog"
	i74 "log/syslog"
	i76 "math/big"
	i79 "math/rand"
	i80 "math/rand/v2"
	i81 "mime"
	i82 "mime/multipart"
	i83 "mime/quotedprintable"
	i84 "net"
	i85 "net/http"
	i86 "net/http/cgi"
	i87 "net/http/cookiejar"
	i89 "net/http/httptest"
	i90 "net/http/httptrace"
	i91 "net/http/httputil"
	i93 "net/mail"
	i94 "net/netip"
	i95 "net/rpc"
	i97 "net/smtp"
	i98 "net/textproto"
	i99 "net/url"
	i100 "os"
	i101 "os/exec"
	i103 "os/user"
	i106 "plugin"
	i107 "reflect"
	i108 "regexp"
	i109 "regexp/syntax"
	i110 "runtime"
	i111 "runtime/cgo"
	i113 "runtime/debug"
	i114 "runtime/metrics"
	i115 "runtime/pprof"
	i116 "runtime/trace"
	i118 "strconv"
	i119 "strings"
	i120 "sync"
	i121 "sync/atomic"
	i122 "testing"
	i124 "testing/quick"
	i127 "text/scanner"
	i128 "text/tabwriter"
	i129 "text/template"
	i130 "text/template/parse"
	i131 "time"
	i132 "unicode"
)

// stdtypes maps package paths to their exported types as reflect.Value not reflect.Type
var stdtypes = map[string]map[string]reflect.Value{}

func init() {
	stdtypes["archive/tar"] = map[string]reflect.Value{
		"Format": makeReflect[i1.Format](),
		"Header": makeReflect[i1.Header](),
		"Reader": makeReflect[i1.Reader](),
		"Writer": makeReflect[i1.Writer](),
	}
	stdtypes["archive/zip"] = map[string]reflect.Value{
		"File": makeReflect[i2.File](),
		"FileHeader": makeReflect[i2.FileHeader](),
		"ReadCloser": makeReflect[i2.ReadCloser](),
		"Reader": makeReflect[i2.Reader](),
		"Writer": makeReflect[i2.Writer](),
	}
	stdtypes["bufio"] = map[string]reflect.Value{
		"ReadWriter": makeReflect[i3.ReadWriter](),
		"Reader": makeReflect[i3.Reader](),
		"Scanner": makeReflect[i3.Scanner](),
		"Writer": makeReflect[i3.Writer](),
	}
	stdtypes["bytes"] = map[string]reflect.Value{
		"Buffer": makeReflect[i4.Buffer](),
		"Reader": makeReflect[i4.Reader](),
	}
	stdtypes["compress/bzip2"] = map[string]reflect.Value{
		"StructuralError": makeReflect[i5.StructuralError](),
	}
	stdtypes["compress/flate"] = map[string]reflect.Value{
		"CorruptInputError": makeReflect[i6.CorruptInputError](),
		"InternalError": makeReflect[i6.InternalError](),
		"ReadError": makeReflect[i6.ReadError](),
		"WriteError": makeReflect[i6.WriteError](),
		"Writer": makeReflect[i6.Writer](),
	}
	stdtypes["compress/gzip"] = map[string]reflect.Value{
		"Header": makeReflect[i7.Header](),
		"Reader": makeReflect[i7.Reader](),
		"Writer": makeReflect[i7.Writer](),
	}
	stdtypes["compress/lzw"] = map[string]reflect.Value{
		"Order": makeReflect[i8.Order](),
		"Reader": makeReflect[i8.Reader](),
		"Writer": makeReflect[i8.Writer](),
	}
	stdtypes["compress/zlib"] = map[string]reflect.Value{
		"Writer": makeReflect[i9.Writer](),
	}
	stdtypes["container/list"] = map[string]reflect.Value{
		"Element": makeReflect[i11.Element](),
		"List": makeReflect[i11.List](),
	}
	stdtypes["container/ring"] = map[string]reflect.Value{
		"Ring": makeReflect[i12.Ring](),
	}
	stdtypes["crypto"] = map[string]reflect.Value{
		"DecrypterOpts": makeReflect[i14.DecrypterOpts](),
		"Hash": makeReflect[i14.Hash](),
		"PrivateKey": makeReflect[i14.PrivateKey](),
		"PublicKey": makeReflect[i14.PublicKey](),
	}
	stdtypes["crypto/aes"] = map[string]reflect.Value{
		"KeySizeError": makeReflect[i15.KeySizeError](),
	}
	stdtypes["crypto/cipher"] = map[string]reflect.Value{
		"StreamReader": makeReflect[i16.StreamReader](),
		"StreamWriter": makeReflect[i16.StreamWriter](),
	}
	stdtypes["crypto/des"] = map[string]reflect.Value{
		"KeySizeError": makeReflect[i17.KeySizeError](),
	}
	stdtypes["crypto/dsa"] = map[string]reflect.Value{
		"ParameterSizes": makeReflect[i18.ParameterSizes](),
		"Parameters": makeReflect[i18.Parameters](),
		"PrivateKey": makeReflect[i18.PrivateKey](),
		"PublicKey": makeReflect[i18.PublicKey](),
	}
	stdtypes["crypto/ecdh"] = map[string]reflect.Value{
		"PrivateKey": makeReflect[i19.PrivateKey](),
		"PublicKey": makeReflect[i19.PublicKey](),
	}
	stdtypes["crypto/ecdsa"] = map[string]reflect.Value{
		"PrivateKey": makeReflect[i20.PrivateKey](),
		"PublicKey": makeReflect[i20.PublicKey](),
	}
	stdtypes["crypto/ed25519"] = map[string]reflect.Value{
		"Options": makeReflect[i21.Options](),
	}
	stdtypes["crypto/elliptic"] = map[string]reflect.Value{
		"CurveParams": makeReflect[i22.CurveParams](),
	}
	stdtypes["crypto/mlkem"] = map[string]reflect.Value{
		"DecapsulationKey1024": makeReflect[i26.DecapsulationKey1024](),
		"DecapsulationKey768": makeReflect[i26.DecapsulationKey768](),
		"EncapsulationKey1024": makeReflect[i26.EncapsulationKey1024](),
		"EncapsulationKey768": makeReflect[i26.EncapsulationKey768](),
	}
	stdtypes["crypto/rc4"] = map[string]reflect.Value{
		"Cipher": makeReflect[i28.Cipher](),
		"KeySizeError": makeReflect[i28.KeySizeError](),
	}
	stdtypes["crypto/rsa"] = map[string]reflect.Value{
		"CRTValue": makeReflect[i29.CRTValue](),
		"OAEPOptions": makeReflect[i29.OAEPOptions](),
		"PKCS1v15DecryptOptions": makeReflect[i29.PKCS1v15DecryptOptions](),
		"PSSOptions": makeReflect[i29.PSSOptions](),
		"PrecomputedValues": makeReflect[i29.PrecomputedValues](),
		"PrivateKey": makeReflect[i29.PrivateKey](),
		"PublicKey": makeReflect[i29.PublicKey](),
	}
	stdtypes["crypto/sha3"] = map[string]reflect.Value{
		"SHA3": makeReflect[i32.SHA3](),
		"SHAKE": makeReflect[i32.SHAKE](),
	}
	stdtypes["crypto/tls"] = map[string]reflect.Value{
		"AlertError": makeReflect[i35.AlertError](),
		"Certificate": makeReflect[i35.Certificate](),
		"CertificateRequestInfo": makeReflect[i35.CertificateRequestInfo](),
		"CertificateVerificationError": makeReflect[i35.CertificateVerificationError](),
		"CipherSuite": makeReflect[i35.CipherSuite](),
		"ClientAuthType": makeReflect[i35.ClientAuthType](),
		"ClientHelloInfo": makeReflect[i35.ClientHelloInfo](),
		"ClientSessionState": makeReflect[i35.ClientSessionState](),
		"Config": makeReflect[i35.Config](),
		"Conn": makeReflect[i35.Conn](),
		"ConnectionState": makeReflect[i35.ConnectionState](),
		"CurveID": makeReflect[i35.CurveID](),
		"Dialer": makeReflect[i35.Dialer](),
		"ECHRejectionError": makeReflect[i35.ECHRejectionError](),
		"EncryptedClientHelloKey": makeReflect[i35.EncryptedClientHelloKey](),
		"QUICConfig": makeReflect[i35.QUICConfig](),
		"QUICConn": makeReflect[i35.QUICConn](),
		"QUICEncryptionLevel": makeReflect[i35.QUICEncryptionLevel](),
		"QUICEvent": makeReflect[i35.QUICEvent](),
		"QUICEventKind": makeReflect[i35.QUICEventKind](),
		"QUICSessionTicketOptions": makeReflect[i35.QUICSessionTicketOptions](),
		"RecordHeaderError": makeReflect[i35.RecordHeaderError](),
		"RenegotiationSupport": makeReflect[i35.RenegotiationSupport](),
		"SessionState": makeReflect[i35.SessionState](),
		"SignatureScheme": makeReflect[i35.SignatureScheme](),
	}
	stdtypes["crypto/x509"] = map[string]reflect.Value{
		"CertPool": makeReflect[i36.CertPool](),
		"Certificate": makeReflect[i36.Certificate](),
		"CertificateInvalidError": makeReflect[i36.CertificateInvalidError](),
		"CertificateRequest": makeReflect[i36.CertificateRequest](),
		"ConstraintViolationError": makeReflect[i36.ConstraintViolationError](),
		"ExtKeyUsage": makeReflect[i36.ExtKeyUsage](),
		"HostnameError": makeReflect[i36.HostnameError](),
		"InsecureAlgorithmError": makeReflect[i36.InsecureAlgorithmError](),
		"InvalidReason": makeReflect[i36.InvalidReason](),
		"KeyUsage": makeReflect[i36.KeyUsage](),
		"OID": makeReflect[i36.OID](),
		"PEMCipher": makeReflect[i36.PEMCipher](),
		"PolicyMapping": makeReflect[i36.PolicyMapping](),
		"PublicKeyAlgorithm": makeReflect[i36.PublicKeyAlgorithm](),
		"RevocationList": makeReflect[i36.RevocationList](),
		"RevocationListEntry": makeReflect[i36.RevocationListEntry](),
		"SignatureAlgorithm": makeReflect[i36.SignatureAlgorithm](),
		"SystemRootsError": makeReflect[i36.SystemRootsError](),
		"UnhandledCriticalExtension": makeReflect[i36.UnhandledCriticalExtension](),
		"UnknownAuthorityError": makeReflect[i36.UnknownAuthorityError](),
		"VerifyOptions": makeReflect[i36.VerifyOptions](),
	}
	stdtypes["database/sql"] = map[string]reflect.Value{
		"ColumnType": makeReflect[i37.ColumnType](),
		"Conn": makeReflect[i37.Conn](),
		"DB": makeReflect[i37.DB](),
		"DBStats": makeReflect[i37.DBStats](),
		"IsolationLevel": makeReflect[i37.IsolationLevel](),
		"NamedArg": makeReflect[i37.NamedArg](),
		"NullBool": makeReflect[i37.NullBool](),
		"NullByte": makeReflect[i37.NullByte](),
		"NullFloat64": makeReflect[i37.NullFloat64](),
		"NullInt16": makeReflect[i37.NullInt16](),
		"NullInt32": makeReflect[i37.NullInt32](),
		"NullInt64": makeReflect[i37.NullInt64](),
		"NullString": makeReflect[i37.NullString](),
		"NullTime": makeReflect[i37.NullTime](),
		"Out": makeReflect[i37.Out](),
		"Row": makeReflect[i37.Row](),
		"Rows": makeReflect[i37.Rows](),
		"Stmt": makeReflect[i37.Stmt](),
		"Tx": makeReflect[i37.Tx](),
		"TxOptions": makeReflect[i37.TxOptions](),
	}
	stdtypes["database/sql/driver"] = map[string]reflect.Value{
		"IsolationLevel": makeReflect[i38.IsolationLevel](),
		"NamedValue": makeReflect[i38.NamedValue](),
		"NotNull": makeReflect[i38.NotNull](),
		"Null": makeReflect[i38.Null](),
		"RowsAffected": makeReflect[i38.RowsAffected](),
		"TxOptions": makeReflect[i38.TxOptions](),
		"Value": makeReflect[i38.Value](),
	}
	stdtypes["encoding/ascii85"] = map[string]reflect.Value{
		"CorruptInputError": makeReflect[i39.CorruptInputError](),
	}
	stdtypes["encoding/asn1"] = map[string]reflect.Value{
		"BitString": makeReflect[i40.BitString](),
		"Enumerated": makeReflect[i40.Enumerated](),
		"Flag": makeReflect[i40.Flag](),
		"RawValue": makeReflect[i40.RawValue](),
		"StructuralError": makeReflect[i40.StructuralError](),
		"SyntaxError": makeReflect[i40.SyntaxError](),
	}
	stdtypes["encoding/base32"] = map[string]reflect.Value{
		"CorruptInputError": makeReflect[i41.CorruptInputError](),
		"Encoding": makeReflect[i41.Encoding](),
	}
	stdtypes["encoding/base64"] = map[string]reflect.Value{
		"CorruptInputError": makeReflect[i42.CorruptInputError](),
		"Encoding": makeReflect[i42.Encoding](),
	}
	stdtypes["encoding/csv"] = map[string]reflect.Value{
		"ParseError": makeReflect[i44.ParseError](),
		"Reader": makeReflect[i44.Reader](),
		"Writer": makeReflect[i44.Writer](),
	}
	stdtypes["encoding/gob"] = map[string]reflect.Value{
		"CommonType": makeReflect[i45.CommonType](),
		"Decoder": makeReflect[i45.Decoder](),
		"Encoder": makeReflect[i45.Encoder](),
	}
	stdtypes["encoding/hex"] = map[string]reflect.Value{
		"InvalidByteError": makeReflect[i46.InvalidByteError](),
	}
	stdtypes["encoding/json"] = map[string]reflect.Value{
		"Decoder": makeReflect[i47.Decoder](),
		"Delim": makeReflect[i47.Delim](),
		"Encoder": makeReflect[i47.Encoder](),
		"InvalidUTF8Error": makeReflect[i47.InvalidUTF8Error](),
		"InvalidUnmarshalError": makeReflect[i47.InvalidUnmarshalError](),
		"MarshalerError": makeReflect[i47.MarshalerError](),
		"Number": makeReflect[i47.Number](),
		"SyntaxError": makeReflect[i47.SyntaxError](),
		"Token": makeReflect[i47.Token](),
		"UnmarshalFieldError": makeReflect[i47.UnmarshalFieldError](),
		"UnmarshalTypeError": makeReflect[i47.UnmarshalTypeError](),
		"UnsupportedTypeError": makeReflect[i47.UnsupportedTypeError](),
		"UnsupportedValueError": makeReflect[i47.UnsupportedValueError](),
	}
	stdtypes["encoding/pem"] = map[string]reflect.Value{
		"Block": makeReflect[i48.Block](),
	}
	stdtypes["encoding/xml"] = map[string]reflect.Value{
		"Attr": makeReflect[i49.Attr](),
		"Decoder": makeReflect[i49.Decoder](),
		"Encoder": makeReflect[i49.Encoder](),
		"EndElement": makeReflect[i49.EndElement](),
		"Name": makeReflect[i49.Name](),
		"ProcInst": makeReflect[i49.ProcInst](),
		"StartElement": makeReflect[i49.StartElement](),
		"SyntaxError": makeReflect[i49.SyntaxError](),
		"TagPathError": makeReflect[i49.TagPathError](),
		"Token": makeReflect[i49.Token](),
		"UnmarshalError": makeReflect[i49.UnmarshalError](),
		"UnsupportedTypeError": makeReflect[i49.UnsupportedTypeError](),
	}
	stdtypes["expvar"] = map[string]reflect.Value{
		"Float": makeReflect[i51.Float](),
		"Int": makeReflect[i51.Int](),
		"KeyValue": makeReflect[i51.KeyValue](),
		"Map": makeReflect[i51.Map](),
		"String": makeReflect[i51.String](),
	}
	stdtypes["flag"] = map[string]reflect.Value{
		"ErrorHandling": makeReflect[i52.ErrorHandling](),
		"Flag": makeReflect[i52.Flag](),
		"FlagSet": makeReflect[i52.FlagSet](),
	}
	stdtypes["hash/maphash"] = map[string]reflect.Value{
		"Hash": makeReflect[i58.Hash](),
		"Seed": makeReflect[i58.Seed](),
	}
	stdtypes["html/template"] = map[string]reflect.Value{
		"CSS": makeReflect[i60.CSS](),
		"Error": makeReflect[i60.Error](),
		"ErrorCode": makeReflect[i60.ErrorCode](),
		"HTML": makeReflect[i60.HTML](),
		"HTMLAttr": makeReflect[i60.HTMLAttr](),
		"JS": makeReflect[i60.JS](),
		"JSStr": makeReflect[i60.JSStr](),
		"Srcset": makeReflect[i60.Srcset](),
		"Template": makeReflect[i60.Template](),
		"URL": makeReflect[i60.URL](),
	}
	stdtypes["image"] = map[string]reflect.Value{
		"Alpha": makeReflect[i61.Alpha](),
		"Alpha16": makeReflect[i61.Alpha16](),
		"CMYK": makeReflect[i61.CMYK](),
		"Config": makeReflect[i61.Config](),
		"Gray": makeReflect[i61.Gray](),
		"Gray16": makeReflect[i61.Gray16](),
		"NRGBA": makeReflect[i61.NRGBA](),
		"NRGBA64": makeReflect[i61.NRGBA64](),
		"NYCbCrA": makeReflect[i61.NYCbCrA](),
		"Paletted": makeReflect[i61.Paletted](),
		"Point": makeReflect[i61.Point](),
		"RGBA": makeReflect[i61.RGBA](),
		"RGBA64": makeReflect[i61.RGBA64](),
		"Rectangle": makeReflect[i61.Rectangle](),
		"Uniform": makeReflect[i61.Uniform](),
		"YCbCr": makeReflect[i61.YCbCr](),
		"YCbCrSubsampleRatio": makeReflect[i61.YCbCrSubsampleRatio](),
	}
	stdtypes["image/color"] = map[string]reflect.Value{
		"Alpha": makeReflect[i62.Alpha](),
		"Alpha16": makeReflect[i62.Alpha16](),
		"CMYK": makeReflect[i62.CMYK](),
		"Gray": makeReflect[i62.Gray](),
		"Gray16": makeReflect[i62.Gray16](),
		"NRGBA": makeReflect[i62.NRGBA](),
		"NRGBA64": makeReflect[i62.NRGBA64](),
		"NYCbCrA": makeReflect[i62.NYCbCrA](),
		"RGBA": makeReflect[i62.RGBA](),
		"RGBA64": makeReflect[i62.RGBA64](),
		"YCbCr": makeReflect[i62.YCbCr](),
	}
	stdtypes["image/draw"] = map[string]reflect.Value{
		"Op": makeReflect[i64.Op](),
	}
	stdtypes["image/gif"] = map[string]reflect.Value{
		"GIF": makeReflect[i65.GIF](),
		"Options": makeReflect[i65.Options](),
	}
	stdtypes["image/jpeg"] = map[string]reflect.Value{
		"FormatError": makeReflect[i66.FormatError](),
		"Options": makeReflect[i66.Options](),
		"UnsupportedError": makeReflect[i66.UnsupportedError](),
	}
	stdtypes["image/png"] = map[string]reflect.Value{
		"CompressionLevel": makeReflect[i67.CompressionLevel](),
		"Encoder": makeReflect[i67.Encoder](),
		"EncoderBuffer": makeReflect[i67.EncoderBuffer](),
		"FormatError": makeReflect[i67.FormatError](),
		"UnsupportedError": makeReflect[i67.UnsupportedError](),
	}
	stdtypes["index/suffixarray"] = map[string]reflect.Value{
		"Index": makeReflect[i68.Index](),
	}
	stdtypes["io"] = map[string]reflect.Value{
		"LimitedReader": makeReflect[i69.LimitedReader](),
		"OffsetWriter": makeReflect[i69.OffsetWriter](),
		"PipeReader": makeReflect[i69.PipeReader](),
		"PipeWriter": makeReflect[i69.PipeWriter](),
		"SectionReader": makeReflect[i69.SectionReader](),
	}
	stdtypes["io/fs"] = map[string]reflect.Value{
		"FileMode": makeReflect[i70.FileMode](),
		"PathError": makeReflect[i70.PathError](),
	}
	stdtypes["log"] = map[string]reflect.Value{
		"Logger": makeReflect[i72.Logger](),
	}
	stdtypes["log/slog"] = map[string]reflect.Value{
		"Attr": makeReflect[i73.Attr](),
		"HandlerOptions": makeReflect[i73.HandlerOptions](),
		"JSONHandler": makeReflect[i73.JSONHandler](),
		"Kind": makeReflect[i73.Kind](),
		"Level": makeReflect[i73.Level](),
		"LevelVar": makeReflect[i73.LevelVar](),
		"Logger": makeReflect[i73.Logger](),
		"MultiHandler": makeReflect[i73.MultiHandler](),
		"Record": makeReflect[i73.Record](),
		"Source": makeReflect[i73.Source](),
		"TextHandler": makeReflect[i73.TextHandler](),
		"Value": makeReflect[i73.Value](),
	}
	stdtypes["log/syslog"] = map[string]reflect.Value{
		"Priority": makeReflect[i74.Priority](),
		"Writer": makeReflect[i74.Writer](),
	}
	stdtypes["math/big"] = map[string]reflect.Value{
		"Accuracy": makeReflect[i76.Accuracy](),
		"ErrNaN": makeReflect[i76.ErrNaN](),
		"Float": makeReflect[i76.Float](),
		"Int": makeReflect[i76.Int](),
		"Rat": makeReflect[i76.Rat](),
		"RoundingMode": makeReflect[i76.RoundingMode](),
		"Word": makeReflect[i76.Word](),
	}
	stdtypes["math/rand"] = map[string]reflect.Value{
		"Rand": makeReflect[i79.Rand](),
		"Zipf": makeReflect[i79.Zipf](),
	}
	stdtypes["math/rand/v2"] = map[string]reflect.Value{
		"ChaCha8": makeReflect[i80.ChaCha8](),
		"PCG": makeReflect[i80.PCG](),
		"Rand": makeReflect[i80.Rand](),
		"Zipf": makeReflect[i80.Zipf](),
	}
	stdtypes["mime"] = map[string]reflect.Value{
		"WordDecoder": makeReflect[i81.WordDecoder](),
		"WordEncoder": makeReflect[i81.WordEncoder](),
	}
	stdtypes["mime/multipart"] = map[string]reflect.Value{
		"FileHeader": makeReflect[i82.FileHeader](),
		"Form": makeReflect[i82.Form](),
		"Part": makeReflect[i82.Part](),
		"Reader": makeReflect[i82.Reader](),
		"Writer": makeReflect[i82.Writer](),
	}
	stdtypes["mime/quotedprintable"] = map[string]reflect.Value{
		"Reader": makeReflect[i83.Reader](),
		"Writer": makeReflect[i83.Writer](),
	}
	stdtypes["net"] = map[string]reflect.Value{
		"AddrError": makeReflect[i84.AddrError](),
		"DNSConfigError": makeReflect[i84.DNSConfigError](),
		"DNSError": makeReflect[i84.DNSError](),
		"Dialer": makeReflect[i84.Dialer](),
		"Flags": makeReflect[i84.Flags](),
		"IPAddr": makeReflect[i84.IPAddr](),
		"IPConn": makeReflect[i84.IPConn](),
		"IPNet": makeReflect[i84.IPNet](),
		"Interface": makeReflect[i84.Interface](),
		"InvalidAddrError": makeReflect[i84.InvalidAddrError](),
		"KeepAliveConfig": makeReflect[i84.KeepAliveConfig](),
		"ListenConfig": makeReflect[i84.ListenConfig](),
		"MX": makeReflect[i84.MX](),
		"NS": makeReflect[i84.NS](),
		"OpError": makeReflect[i84.OpError](),
		"ParseError": makeReflect[i84.ParseError](),
		"Resolver": makeReflect[i84.Resolver](),
		"SRV": makeReflect[i84.SRV](),
		"TCPAddr": makeReflect[i84.TCPAddr](),
		"TCPConn": makeReflect[i84.TCPConn](),
		"TCPListener": makeReflect[i84.TCPListener](),
		"UDPAddr": makeReflect[i84.UDPAddr](),
		"UDPConn": makeReflect[i84.UDPConn](),
		"UnixAddr": makeReflect[i84.UnixAddr](),
		"UnixConn": makeReflect[i84.UnixConn](),
		"UnixListener": makeReflect[i84.UnixListener](),
		"UnknownNetworkError": makeReflect[i84.UnknownNetworkError](),
	}
	stdtypes["net/http"] = map[string]reflect.Value{
		"Client": makeReflect[i85.Client](),
		"ClientConn": makeReflect[i85.ClientConn](),
		"ConnState": makeReflect[i85.ConnState](),
		"Cookie": makeReflect[i85.Cookie](),
		"CrossOriginProtection": makeReflect[i85.CrossOriginProtection](),
		"Dir": makeReflect[i85.Dir](),
		"HTTP2Config": makeReflect[i85.HTTP2Config](),
		"MaxBytesError": makeReflect[i85.MaxBytesError](),
		"ProtocolError": makeReflect[i85.ProtocolError](),
		"Protocols": makeReflect[i85.Protocols](),
		"PushOptions": makeReflect[i85.PushOptions](),
		"Request": makeReflect[i85.Request](),
		"Response": makeReflect[i85.Response](),
		"ResponseController": makeReflect[i85.ResponseController](),
		"SameSite": makeReflect[i85.SameSite](),
		"ServeMux": makeReflect[i85.ServeMux](),
		"Server": makeReflect[i85.Server](),
		"Transport": makeReflect[i85.Transport](),
	}
	stdtypes["net/http/cgi"] = map[string]reflect.Value{
		"Handler": makeReflect[i86.Handler](),
	}
	stdtypes["net/http/cookiejar"] = map[string]reflect.Value{
		"Jar": makeReflect[i87.Jar](),
		"Options": makeReflect[i87.Options](),
	}
	stdtypes["net/http/httptest"] = map[string]reflect.Value{
		"ResponseRecorder": makeReflect[i89.ResponseRecorder](),
		"Server": makeReflect[i89.Server](),
	}
	stdtypes["net/http/httptrace"] = map[string]reflect.Value{
		"ClientTrace": makeReflect[i90.ClientTrace](),
		"DNSDoneInfo": makeReflect[i90.DNSDoneInfo](),
		"DNSStartInfo": makeReflect[i90.DNSStartInfo](),
		"GotConnInfo": makeReflect[i90.GotConnInfo](),
		"WroteRequestInfo": makeReflect[i90.WroteRequestInfo](),
	}
	stdtypes["net/http/httputil"] = map[string]reflect.Value{
		"ClientConn": makeReflect[i91.ClientConn](),
		"ProxyRequest": makeReflect[i91.ProxyRequest](),
		"ReverseProxy": makeReflect[i91.ReverseProxy](),
		"ServerConn": makeReflect[i91.ServerConn](),
	}
	stdtypes["net/mail"] = map[string]reflect.Value{
		"Address": makeReflect[i93.Address](),
		"AddressParser": makeReflect[i93.AddressParser](),
		"Message": makeReflect[i93.Message](),
	}
	stdtypes["net/netip"] = map[string]reflect.Value{
		"Addr": makeReflect[i94.Addr](),
		"AddrPort": makeReflect[i94.AddrPort](),
		"Prefix": makeReflect[i94.Prefix](),
	}
	stdtypes["net/rpc"] = map[string]reflect.Value{
		"Call": makeReflect[i95.Call](),
		"Client": makeReflect[i95.Client](),
		"Request": makeReflect[i95.Request](),
		"Response": makeReflect[i95.Response](),
		"Server": makeReflect[i95.Server](),
		"ServerError": makeReflect[i95.ServerError](),
	}
	stdtypes["net/smtp"] = map[string]reflect.Value{
		"Client": makeReflect[i97.Client](),
		"ServerInfo": makeReflect[i97.ServerInfo](),
	}
	stdtypes["net/textproto"] = map[string]reflect.Value{
		"Conn": makeReflect[i98.Conn](),
		"Error": makeReflect[i98.Error](),
		"Pipeline": makeReflect[i98.Pipeline](),
		"ProtocolError": makeReflect[i98.ProtocolError](),
		"Reader": makeReflect[i98.Reader](),
		"Writer": makeReflect[i98.Writer](),
	}
	stdtypes["net/url"] = map[string]reflect.Value{
		"Error": makeReflect[i99.Error](),
		"EscapeError": makeReflect[i99.EscapeError](),
		"InvalidHostError": makeReflect[i99.InvalidHostError](),
		"URL": makeReflect[i99.URL](),
		"Userinfo": makeReflect[i99.Userinfo](),
	}
	stdtypes["os"] = map[string]reflect.Value{
		"File": makeReflect[i100.File](),
		"LinkError": makeReflect[i100.LinkError](),
		"ProcAttr": makeReflect[i100.ProcAttr](),
		"Process": makeReflect[i100.Process](),
		"ProcessState": makeReflect[i100.ProcessState](),
		"Root": makeReflect[i100.Root](),
		"SyscallError": makeReflect[i100.SyscallError](),
	}
	stdtypes["os/exec"] = map[string]reflect.Value{
		"Cmd": makeReflect[i101.Cmd](),
		"Error": makeReflect[i101.Error](),
		"ExitError": makeReflect[i101.ExitError](),
	}
	stdtypes["os/user"] = map[string]reflect.Value{
		"Group": makeReflect[i103.Group](),
		"UnknownGroupError": makeReflect[i103.UnknownGroupError](),
		"UnknownGroupIdError": makeReflect[i103.UnknownGroupIdError](),
		"UnknownUserError": makeReflect[i103.UnknownUserError](),
		"UnknownUserIdError": makeReflect[i103.UnknownUserIdError](),
		"User": makeReflect[i103.User](),
	}
	stdtypes["plugin"] = map[string]reflect.Value{
		"Plugin": makeReflect[i106.Plugin](),
		"Symbol": makeReflect[i106.Symbol](),
	}
	stdtypes["reflect"] = map[string]reflect.Value{
		"ChanDir": makeReflect[i107.ChanDir](),
		"Kind": makeReflect[i107.Kind](),
		"MapIter": makeReflect[i107.MapIter](),
		"Method": makeReflect[i107.Method](),
		"SelectCase": makeReflect[i107.SelectCase](),
		"SelectDir": makeReflect[i107.SelectDir](),
		"SliceHeader": makeReflect[i107.SliceHeader](),
		"StringHeader": makeReflect[i107.StringHeader](),
		"StructField": makeReflect[i107.StructField](),
		"StructTag": makeReflect[i107.StructTag](),
		"Value": makeReflect[i107.Value](),
		"ValueError": makeReflect[i107.ValueError](),
	}
	stdtypes["regexp"] = map[string]reflect.Value{
		"Regexp": makeReflect[i108.Regexp](),
	}
	stdtypes["regexp/syntax"] = map[string]reflect.Value{
		"EmptyOp": makeReflect[i109.EmptyOp](),
		"Error": makeReflect[i109.Error](),
		"ErrorCode": makeReflect[i109.ErrorCode](),
		"Flags": makeReflect[i109.Flags](),
		"Inst": makeReflect[i109.Inst](),
		"InstOp": makeReflect[i109.InstOp](),
		"Op": makeReflect[i109.Op](),
		"Prog": makeReflect[i109.Prog](),
		"Regexp": makeReflect[i109.Regexp](),
	}
	stdtypes["runtime"] = map[string]reflect.Value{
		"BlockProfileRecord": makeReflect[i110.BlockProfileRecord](),
		"Cleanup": makeReflect[i110.Cleanup](),
		"Frame": makeReflect[i110.Frame](),
		"Frames": makeReflect[i110.Frames](),
		"Func": makeReflect[i110.Func](),
		"MemProfileRecord": makeReflect[i110.MemProfileRecord](),
		"MemStats": makeReflect[i110.MemStats](),
		"PanicNilError": makeReflect[i110.PanicNilError](),
		"Pinner": makeReflect[i110.Pinner](),
		"StackRecord": makeReflect[i110.StackRecord](),
		"TypeAssertionError": makeReflect[i110.TypeAssertionError](),
	}
	stdtypes["runtime/cgo"] = map[string]reflect.Value{
		"Handle": makeReflect[i111.Handle](),
	}
	stdtypes["runtime/debug"] = map[string]reflect.Value{
		"BuildInfo": makeReflect[i113.BuildInfo](),
		"BuildSetting": makeReflect[i113.BuildSetting](),
		"CrashOptions": makeReflect[i113.CrashOptions](),
		"GCStats": makeReflect[i113.GCStats](),
		"Module": makeReflect[i113.Module](),
	}
	stdtypes["runtime/metrics"] = map[string]reflect.Value{
		"Description": makeReflect[i114.Description](),
		"Float64Histogram": makeReflect[i114.Float64Histogram](),
		"Sample": makeReflect[i114.Sample](),
		"Value": makeReflect[i114.Value](),
		"ValueKind": makeReflect[i114.ValueKind](),
	}
	stdtypes["runtime/pprof"] = map[string]reflect.Value{
		"LabelSet": makeReflect[i115.LabelSet](),
		"Profile": makeReflect[i115.Profile](),
	}
	stdtypes["runtime/trace"] = map[string]reflect.Value{
		"FlightRecorder": makeReflect[i116.FlightRecorder](),
		"FlightRecorderConfig": makeReflect[i116.FlightRecorderConfig](),
		"Region": makeReflect[i116.Region](),
		"Task": makeReflect[i116.Task](),
	}
	stdtypes["strconv"] = map[string]reflect.Value{
		"NumError": makeReflect[i118.NumError](),
	}
	stdtypes["strings"] = map[string]reflect.Value{
		"Builder": makeReflect[i119.Builder](),
		"Reader": makeReflect[i119.Reader](),
		"Replacer": makeReflect[i119.Replacer](),
	}
	stdtypes["sync"] = map[string]reflect.Value{
		"Cond": makeReflect[i120.Cond](),
		"Map": makeReflect[i120.Map](),
		"Mutex": makeReflect[i120.Mutex](),
		"Once": makeReflect[i120.Once](),
		"Pool": makeReflect[i120.Pool](),
		"RWMutex": makeReflect[i120.RWMutex](),
		"WaitGroup": makeReflect[i120.WaitGroup](),
	}
	stdtypes["sync/atomic"] = map[string]reflect.Value{
		"Bool": makeReflect[i121.Bool](),
		"Int32": makeReflect[i121.Int32](),
		"Int64": makeReflect[i121.Int64](),
		"Uint32": makeReflect[i121.Uint32](),
		"Uint64": makeReflect[i121.Uint64](),
		"Uintptr": makeReflect[i121.Uintptr](),
		"Value": makeReflect[i121.Value](),
	}
	stdtypes["testing"] = map[string]reflect.Value{
		"B": makeReflect[i122.B](),
		"BenchmarkResult": makeReflect[i122.BenchmarkResult](),
		"Cover": makeReflect[i122.Cover](),
		"CoverBlock": makeReflect[i122.CoverBlock](),
		"F": makeReflect[i122.F](),
		"InternalBenchmark": makeReflect[i122.InternalBenchmark](),
		"InternalExample": makeReflect[i122.InternalExample](),
		"InternalFuzzTarget": makeReflect[i122.InternalFuzzTarget](),
		"InternalTest": makeReflect[i122.InternalTest](),
		"M": makeReflect[i122.M](),
		"PB": makeReflect[i122.PB](),
		"T": makeReflect[i122.T](),
	}
	stdtypes["testing/quick"] = map[string]reflect.Value{
		"CheckEqualError": makeReflect[i124.CheckEqualError](),
		"CheckError": makeReflect[i124.CheckError](),
		"Config": makeReflect[i124.Config](),
		"SetupError": makeReflect[i124.SetupError](),
	}
	stdtypes["text/scanner"] = map[string]reflect.Value{
		"Position": makeReflect[i127.Position](),
		"Scanner": makeReflect[i127.Scanner](),
	}
	stdtypes["text/tabwriter"] = map[string]reflect.Value{
		"Writer": makeReflect[i128.Writer](),
	}
	stdtypes["text/template"] = map[string]reflect.Value{
		"ExecError": makeReflect[i129.ExecError](),
		"Template": makeReflect[i129.Template](),
	}
	stdtypes["text/template/parse"] = map[string]reflect.Value{
		"ActionNode": makeReflect[i130.ActionNode](),
		"BoolNode": makeReflect[i130.BoolNode](),
		"BranchNode": makeReflect[i130.BranchNode](),
		"BreakNode": makeReflect[i130.BreakNode](),
		"ChainNode": makeReflect[i130.ChainNode](),
		"CommandNode": makeReflect[i130.CommandNode](),
		"CommentNode": makeReflect[i130.CommentNode](),
		"ContinueNode": makeReflect[i130.ContinueNode](),
		"DotNode": makeReflect[i130.DotNode](),
		"FieldNode": makeReflect[i130.FieldNode](),
		"IdentifierNode": makeReflect[i130.IdentifierNode](),
		"IfNode": makeReflect[i130.IfNode](),
		"ListNode": makeReflect[i130.ListNode](),
		"Mode": makeReflect[i130.Mode](),
		"NilNode": makeReflect[i130.NilNode](),
		"NodeType": makeReflect[i130.NodeType](),
		"NumberNode": makeReflect[i130.NumberNode](),
		"PipeNode": makeReflect[i130.PipeNode](),
		"Pos": makeReflect[i130.Pos](),
		"RangeNode": makeReflect[i130.RangeNode](),
		"StringNode": makeReflect[i130.StringNode](),
		"TemplateNode": makeReflect[i130.TemplateNode](),
		"TextNode": makeReflect[i130.TextNode](),
		"Tree": makeReflect[i130.Tree](),
		"VariableNode": makeReflect[i130.VariableNode](),
		"WithNode": makeReflect[i130.WithNode](),
	}
	stdtypes["time"] = map[string]reflect.Value{
		"Duration": makeReflect[i131.Duration](),
		"Location": makeReflect[i131.Location](),
		"Month": makeReflect[i131.Month](),
		"ParseError": makeReflect[i131.ParseError](),
		"Ticker": makeReflect[i131.Ticker](),
		"Time": makeReflect[i131.Time](),
		"Timer": makeReflect[i131.Timer](),
		"Weekday": makeReflect[i131.Weekday](),
	}
	stdtypes["unicode"] = map[string]reflect.Value{
		"CaseRange": makeReflect[i132.CaseRange](),
		"Range16": makeReflect[i132.Range16](),
		"Range32": makeReflect[i132.Range32](),
		"RangeTable": makeReflect[i132.RangeTable](),
	}
}
